name: Docker Publish

on:
  push:
    branches: [ "main" ]
    paths:
      - 'config/model_config.json'  # Trigger only when config change
      - '.github/workflows/docker-publish.yml'
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate config exists
        run: |
          if [ ! -f config/model_config.json ]; then
            echo "❌ config/model_config.json not found!"
            exit 1
          fi
          echo "✅ Config file found"
          cat config/model_config.json

      - name: Train model from config
        run: |
          python src/train_from_config.py \
            --config config/model_config.json \
            --data prompt/final_processed_zudio_data.csv \
            --output models/model.joblib \
            --min-r2 0.5

      - name: Verify model was created
        run: |
          if [ ! -f models/model.joblib ]; then
            echo "❌ Model training failed!"
            exit 1
          fi
          echo "✅ Model trained successfully"
          ls -lh models/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_REPO }}
          tags: |
            type=raw,value=latest
            type=sha
            type=raw,value={{date 'YYYYMMDD-HHmmss'}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/model.joblib
          retention-days: 90